@startuml
package "ODA" {
  [API Gateway] as gw
  [oda-idp] as idp
  [ODA FHIR Service] as fhir
  [oda-phr] as ophr
}

package "KaPA Services" {
  [eIdentification]
}

package "Local services" {
  agent EHR
  [Appointment Service] as avfhir
}

package "Kela Services” {
  [Kanta]
  [Kansa]
  [Omatietovaranto] as phr
}

package "External Services" {
  [Laboratory\nSystem] as lab
  [Laboratory Appointment\nBooking] as labab
  lab --> labab
  lab --> [Kanta]
}

actor Professional
actor Customer
agent Browser

Customer --> Browser
Professional ..> Browser

Browser --> gw
idp --> ophr
gw --> idp
fhir --> ophr
[EHR] --> gw
Professional --> [EHR]
fhir --> lab
fhir --> avfhir
fhir --> [Kanta]
fhir --> [Kansa]
idp --> [eIdentification]
gw --> fhir
[EHR] --> avfhir
fhir --> phr
@enduml
