@startuml
package ODA {
  [oda-idp] as idp
  [oda-phr] as phr
  [ODA FHIR -palvelu] as service
}

package "KaPA" {
  [Suomi.fi-tunnistus] as auth
}

idp ..> [EHR] : Kirjautumistunniste
auth ..> idp : Tunnistautumistieto
phr ..> idp : Ammattilaisen tiedot
[EHR] ..> service : Kirjautumistunniste, HL7 FHIR -resurssipyyntö
service ..> [EHR] : HL7 FHIR -resurssi
@enduml
